name: Deploy React App
on: push
jobs:
  test-name:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3 # встроенные action
      - name: Install dependecies # установка зависимостей
        run: npm ci
      - name: Test application
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    needs: test-name # какой работы необходимо дождаться чтобы зпустить эту работу
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3 # встроенные action
      - name: Install dependecies # установка зависимостей
        run: npm ci
      - name: Lint application
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3 # встроенные action
      - name: Install dependecies # установка зависимостей
        run: npm ci
      - name: BUild application
        run: npm run build
      - name: Deploy
        run: echo Deploying...